### ISSUE TITLE
FluxPrune.jl relies on MaskedArray functions which seem to not exist

### ISSUE THREAD

**Issue by vonpetersenn** [darsnack/FluxPrune.jl#10]
In FluxPrune.jl the MaskedArray functions
`using MaskedArrays: mask, bitmask, freeze, MaskedArray, MaskedSliceArray` are loaded.

However, `bitmask` for example is not defined in `MaskedArrays v0.2.0`:

error message:
``` shell
julia> using MaskedArrays: bitmap
ERROR: UndefVarError: `bitmap` not defined
```
Of the functions `mask`, `bitmask`, `freeze`, `MaskedArray`, `MaskedSliceArray` only `MaskedArray`, and `MaskedSliceArray` seem to be defined in the first place when comparing with the source code of [MaskedArrays](https://github.com/darsnack/MaskedArrays.jl/blob/main/src/MaskedArrays.jl):
```Julia
module MaskedArrays

using GPUArrays
using Adapt

export MaskedArray, MaskedSliceArray

include("types.jl")
include("api.jl")
include("fastops.jl")

end
```

I chose MaskedArrayzs v0.2.0 based on the `Project.toml` in the root folder. Does some other package called MaskedArrays exist, that I somehow overlooked?

**Comment by darsnack** [comment]
If you check the [other files](https://github.com/darsnack/MaskedArrays.jl/tree/main/src) that are included in the code you linked, you'll see definitions for all the functions. The error you are getting is because you are importing `bitmap` which indeed does not exist. The actual function is called `bitmask`.
